# Generated by Django 6.0.6 on 2026-07-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('living_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ielts_requirement', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
