# Generated by Django 6.0.6 on 2026-07-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.BooleanField(default=False)),
                ('ielts', models.BooleanField(default=False)),
                ('sop', models.BooleanField(default=False)),
                ('lor', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('offer_letter', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
