# Generated by Django 6.0.6 on 2026-07-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
